### PR TITLE
Create LICENSE for the repository

### PR DESCRIPTION
**Pull request by HlexNC**
Added the default MIT License. Formatted for Zolara-AI.

### CODE REVIEW

**Review by H8K56 — COMMENTED** [review]
What liscense exist, such that people can not easily sell the software easily , without paying a royalty?

**Comment by HlexNC** [comment]
I don't think open-source works like that, as we are trying to ensure an open and collaborative development. But I will do the research

**Comment by HlexNC** [comment]
The **GNU Affero General Public License v3.0 (AGPL-3.0)** is the best fit from GitHub's commonly used licenses for what you want @H8K56. It compels anyone who modifies and uses your code in a networked environment to also share their modifications. While not prohibiting commercial use, it obliges companies to openly share their changes, which can discourage proprietary use.

**Review by H8K56 — APPROVED** [review]
Thanks for the change and sorry for closing the pr

**Pull request merged**
