### PR TITLE
CodeQL: GitHub Actions for Code Scanning

### PR DESCRIPTION
**Pull request by HlexNC**

### CODE REVIEW

**Review by H8K56 — CHANGES_REQUESTED** [review]
The structure is fine, I think it would be best to define the programming languages that we are going to use exampl pyhton, js,etc. in line 41

**Comment by HlexNC** [comment]
@H8K56 I have made the changes you have requested. The code works now.

**Comment by H8K56** [comment]
@HlexNC  Thanks for the change

**Review by H8K56 — COMMENTED** [review]
Everything looks good

**Comment by HlexNC** [comment]
@H8K56 I still need you to review it, also. Next to every file submitted there is a checkbox to verify that you have reviewed the file.

**Review by H8K56 — CHANGES_REQUESTED** [review]
Should python be in the language, on Line 41

**Comment by HlexNC** [comment]
Yes it should. The reason is that the 2 API's, that will later be containerized, will be written in python

**Review by H8K56 — APPROVED** [review]
Ok, thanks for the input

**Pull request merged**
